GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsInVzZXJOYW1lIjoidGVzdCIsInVzZXJFbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImlhdCI6MTY0Mzg2MjE2MCwiZXhwIjoxNjQzODYyMTgwfQ.3yfKqjSwxdRLaQRkB2KbeHzvLiNd_PWJzvcrtmFhTkY
###

POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "tesdgst",
    "email": "test2@gmail.com",
    "password": "test",
    "confirmPassword": "tasfafest"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "riz@gmail.com",
    "password": "123"
}

###

GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout
